stages:
  - build
  - deploy


include:
  - project: '$DEVOPS_PROJECT_PATH'
    ref: 'main'
    file: 'gitlabci/build/backend/.gitlab-ci.yml'
  - project: '$DEVOPS_PROJECT_PATH'
    ref: 'main'
    file: 'gitlabci/deploy/backend/.gitlab-ci.yml'
  - project: '$DEVOPS_PROJECT_PATH'
    ref: 'main'
    file: 'clients/build/backend/aws/.gitlab-ci.yml'
